//comments are knowing you, ie owing you wowing wooooo
/* char redacted = 'a';*/
char a;
unsigned char b = 255;
const char c = '@';
char* ur_moms_name = "Susanne";

//we need printf
extern int printf(char* fmt,...);

/*cool possibility the C devs went out of their way to not allow :thinkie: */
int add(int a, int b) return a + b;
int sub(int a, int b) return a - b;


int main(int argc, char** argv) {
    char* d = "the condition that distinguishes organisms from inorganic objects and dead organisms, being manifested by growth through metabolism, reproduction, and the power of adaptation to environment through changes originating internally.";
    long unsigned int e = 0xFFFFFFFFFFFFFFFF ^ 0x0000000000000002;
    long int f = -4;

    printf("Anyád neve(your mother's name): %s\n",ur_moms_name);
    printf("Who the fuck needs rand when we can have %u\n",a);
    printf("The meaning of life is: %s\n",d);

    f = (add(f + a,f - a) * 4) / 3;
    e = !(f > 6) ? e & 0xEEEEEEEEEEEEEEEE : e % f;
    e = e | 0x5634563457855784;

    f = f % 4;

    if (e > f && !(e < a)) {
        printf("E biggie\n");
    } 

    if (e >= f || !(e <= f)) {
        goto error;
    }

    //sad
    if (e != (e = 69420)){
        printf("[REDACTED] banned memes yesterday evening.\n");
    }

    return 0;

    error:
        return 1;
}